# Named Entity Recognition (NLP-NER)

In [1]:
import spacy
from nltk import sent_tokenize

In [2]:
!python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ---------------------------------------- 0.0/457.4 MB ? eta -:--:--
      -------------------------------------- 6.6/457.4 MB 40.3 MB/s eta 0:00:12
     - ------------------------------------ 13.6/457.4 MB 35.7 MB/s eta 0:00:13
     - ------------------------------------ 18.9/457.4 MB 33.1 MB/s eta 0:00:14
     - ------------------------------------ 21.5/457.4 MB 27.8 MB/s eta 0:00:16
     -- ----------------------------------- 24.1/457.4 MB 25.0 MB/s eta 0:00:18
     -- ----------------------------------- 27.0/457.4 MB 22.5 MB/s eta 0:00:20
     -- ----------------------------------- 30.4/457.4 MB 21.4 MB/s eta 0:00:20
     -- ----------------------------------- 34.1/457.4 MB 20.8 MB/s eta 0:00:21
     --- ---------------------------------- 37.5/457.4 MB 20.4 MB/s eta 0:00:21
     --- ---------------------------------- 41.2/457.4 MB 20.1 MB/s eta 0:00:21
     --- ---------------------------------- 43.8/457.4 MB 19.3 MB/s eta 0:00:22
     --- ---------------------------------- 45.9/457.4 MB 18.5 MB/s eta 0:00:23
     ---- --------------------------------- 48.2/457.4 MB 17.9 MB/s eta 0:00:23
     ---- --------------------------------- 50.6/457.4 MB 17.4 MB/s eta 0:00:24
     ---- --------------------------------- 52.2/457.4 MB 16.8 MB/s eta 0:00:25
     ---- --------------------------------- 53.2/457.4 MB 16.5 MB/s eta 0:00:25
     ---- --------------------------------- 53.7/457.4 MB 15.2 MB/s eta 0:00:27
     ---- --------------------------------- 56.4/457.4 MB 15.1 MB/s eta 0:00:27
     ---- --------------------------------- 58.2/457.4 MB 14.9 MB/s eta 0:00:27
     ---- --------------------------------- 58.2/457.4 MB 14.9 MB/s eta 0:00:27
     ----- -------------------------------- 60.6/457.4 MB 13.9 MB/s eta 0:00:29
     ----- -------------------------------- 62.9/457.4 MB 13.7 MB/s eta 0:00:29
     ----- -------------------------------- 65.3/457.4 MB 13.6 MB/s eta 0:00:29
     ----- -------------------------------- 67.4/457.4 MB 13.5 MB/s eta 0:00:29
     ----- -------------------------------- 70.0/457.4 MB 13.4 MB/s eta 0:00:29
     ------ ------------------------------- 72.4/457.4 MB 13.4 MB/s eta 0:00:29
     ------ ------------------------------- 75.8/457.4 MB 13.5 MB/s eta 0:00:29
     ------ ------------------------------- 79.2/457.4 MB 13.6 MB/s eta 0:00:28
     ------ ------------------------------- 81.5/457.4 MB 13.6 MB/s eta 0:00:28
     ------ ------------------------------- 81.5/457.4 MB 13.6 MB/s eta 0:00:28
     ------ ------------------------------- 81.5/457.4 MB 13.6 MB/s eta 0:00:28
     ------ ------------------------------- 82.3/457.4 MB 12.4 MB/s eta 0:00:31
     ------- ------------------------------ 84.4/457.4 MB 12.3 MB/s eta 0:00:31
     ------- ------------------------------ 86.0/457.4 MB 12.2 MB/s eta 0:00:31
     ------- ------------------------------ 86.8/457.4 MB 12.0 MB/s eta 0:00:31
     ------- ------------------------------ 88.3/457.4 MB 11.8 MB/s eta 0:00:32
     ------- ------------------------------ 89.1/457.4 MB 11.8 MB/s eta 0:00:32
     ------- ------------------------------ 90.4/457.4 MB 11.4 MB/s eta 0:00:33
     ------- ------------------------------ 91.2/457.4 MB 11.3 MB/s eta 0:00:33
     ------- ------------------------------ 91.2/457.4 MB 11.3 MB/s eta 0:00:33
     ------- ------------------------------ 92.0/457.4 MB 10.8 MB/s eta 0:00:34
     ------- ------------------------------ 92.8/457.4 MB 10.7 MB/s eta 0:00:34
     ------- ------------------------------ 93.6/457.4 MB 10.5 MB/s eta 0:00:35
     ------- ------------------------------ 94.4/457.4 MB 10.3 MB/s eta 0:00:36
     ------- ------------------------------ 95.2/457.4 MB 10.2 MB/s eta 0:00:36
     ------- ------------------------------ 96.2/457.4 MB 10.1 MB/s eta 0:00:36
     -------- ----------------------------- 97.0/457.4 MB 10.0 MB/s eta 0:00:37
     -------- ----------------------------- 97.0/457.4 MB 10.0 MB/s eta 0:00:37
     -------- ------------------------------ 97.5/457.4 MB 9.6 MB/s eta 0:00:38
     -------- ------------------------------ 98.8/457.4 MB 9.5 MB/s eta 0:00:38
     -------- ----------------------------- 100.1/457.4 MB 9.5 MB/s eta 0:00:38
     -------- ----------------------------- 101.4/457.4 MB 9.4 MB/s eta 0:00:38
     -------- ----------------------------- 101.7/457.4 MB 9.2 MB/s eta 0:00:39
     -------- ----------------------------- 103.0/457.4 MB 9.2 MB/s eta 0:00:39
     -------- ----------------------------- 105.1/457.4 MB 9.2 MB/s eta 0:00:39
     -------- ----------------------------- 107.2/457.4 MB 9.2 MB/s eta 0:00:39
     --------- ---------------------------- 109.6/457.4 MB 9.2 MB/s eta 0:00:38
     --------- ---------------------------- 110.9/457.4 MB 9.2 MB/s eta 0:00:38
     --------- ---------------------------- 111.9/457.4 MB 9.1 MB/s eta 0:00:38
     --------- ---------------------------- 111.9/457.4 MB 9.1 MB/s eta 0:00:38
     --------- ---------------------------- 113.8/457.4 MB 8.9 MB/s eta 0:00:39
     --------- ---------------------------- 117.2/457.4 MB 9.0 MB/s eta 0:00:38
     ---------- --------------------------- 122.2/457.4 MB 9.3 MB/s eta 0:00:37
     ---------- --------------------------- 129.2/457.4 MB 9.7 MB/s eta 0:00:34
     ----------- ------------------------- 136.1/457.4 MB 10.0 MB/s eta 0:00:33
     ----------- ------------------------- 142.6/457.4 MB 10.3 MB/s eta 0:00:31
     ----------- ------------------------- 147.3/457.4 MB 10.5 MB/s eta 0:00:30
     ------------ ------------------------ 153.9/457.4 MB 10.8 MB/s eta 0:00:29
     ------------ ------------------------ 159.4/457.4 MB 11.0 MB/s eta 0:00:28
     ------------- ----------------------- 162.3/457.4 MB 11.1 MB/s eta 0:00:27
     ------------- ----------------------- 164.1/457.4 MB 11.0 MB/s eta 0:00:27
     ------------- ----------------------- 165.4/457.4 MB 11.0 MB/s eta 0:00:27
     ------------- ----------------------- 165.4/457.4 MB 11.0 MB/s eta 0:00:27
     ------------- ----------------------- 167.0/457.4 MB 10.8 MB/s eta 0:00:27
     ------------- ----------------------- 172.5/457.4 MB 11.0 MB/s eta 0:00:26
     -------------- ---------------------- 177.2/457.4 MB 11.1 MB/s eta 0:00:26
     -------------- ---------------------- 180.4/457.4 MB 11.2 MB/s eta 0:00:25
     -------------- ---------------------- 183.8/457.4 MB 11.2 MB/s eta 0:00:25
     --------------- --------------------- 187.4/457.4 MB 11.3 MB/s eta 0:00:24
     --------------- --------------------- 191.4/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 195.3/457.4 MB 11.5 MB/s eta 0:00:23
     ---------------- -------------------- 199.5/457.4 MB 11.6 MB/s eta 0:00:23
     ---------------- -------------------- 203.7/457.4 MB 11.7 MB/s eta 0:00:22
     ---------------- -------------------- 208.1/457.4 MB 11.8 MB/s eta 0:00:22
     ----------------- ------------------- 212.6/457.4 MB 11.9 MB/s eta 0:00:21
     ----------------- ------------------- 217.3/457.4 MB 12.0 MB/s eta 0:00:20
     ----------------- ------------------- 221.8/457.4 MB 12.1 MB/s eta 0:00:20
     ------------------ ------------------ 225.4/457.4 MB 12.2 MB/s eta 0:00:20
     ------------------ ------------------ 225.7/457.4 MB 12.2 MB/s eta 0:00:20
     ------------------ ------------------ 228.3/457.4 MB 12.1 MB/s eta 0:00:19
     ------------------ ------------------ 232.3/457.4 MB 12.1 MB/s eta 0:00:19
     ------------------- ----------------- 235.4/457.4 MB 12.2 MB/s eta 0:00:19
     ------------------- ----------------- 238.0/457.4 MB 12.2 MB/s eta 0:00:19
     ------------------- ----------------- 240.4/457.4 MB 12.2 MB/s eta 0:00:18
     ------------------- ----------------- 242.5/457.4 MB 12.1 MB/s eta 0:00:18
     ------------------- ----------------- 244.1/457.4 MB 12.1 MB/s eta 0:00:18
     ------------------- ----------------- 246.4/457.4 MB 12.1 MB/s eta 0:00:18
     -------------------- ---------------- 248.5/457.4 MB 12.1 MB/s eta 0:00:18
     -------------------- ---------------- 248.5/457.4 MB 12.1 MB/s eta 0:00:18
     -------------------- ---------------- 249.3/457.4 MB 11.9 MB/s eta 0:00:18
     -------------------- ---------------- 251.4/457.4 MB 11.8 MB/s eta 0:00:18
     -------------------- ---------------- 254.0/457.4 MB 11.8 MB/s eta 0:00:18
     -------------------- ---------------- 256.9/457.4 MB 11.9 MB/s eta 0:00:17
     -------------------- ---------------- 259.0/457.4 MB 11.8 MB/s eta 0:00:17
     --------------------- --------------- 262.1/457.4 MB 11.9 MB/s eta 0:00:17
     --------------------- --------------- 265.3/457.4 MB 11.8 MB/s eta 0:00:17
     --------------------- --------------- 267.6/457.4 MB 11.7 MB/s eta 0:00:17
     --------------------- --------------- 269.7/457.4 MB 11.6 MB/s eta 0:00:17
     --------------------- --------------- 271.8/457.4 MB 11.5 MB/s eta 0:00:17
     ---------------------- -------------- 273.9/457.4 MB 11.5 MB/s eta 0:00:16
     ---------------------- -------------- 273.9/457.4 MB 11.5 MB/s eta 0:00:16
     ---------------------- -------------- 274.5/457.4 MB 11.3 MB/s eta 0:00:17
     ---------------------- -------------- 277.6/457.4 MB 11.2 MB/s eta 0:00:17
     ---------------------- -------------- 280.0/457.4 MB 11.2 MB/s eta 0:00:16
     ---------------------- -------------- 280.0/457.4 MB 11.2 MB/s eta 0:00:16
     ---------------------- -------------- 281.3/457.4 MB 11.0 MB/s eta 0:00:17
     ---------------------- -------------- 283.1/457.4 MB 11.0 MB/s eta 0:00:16
     ----------------------- ------------- 284.4/457.4 MB 10.9 MB/s eta 0:00:16
     ----------------------- ------------- 286.0/457.4 MB 10.9 MB/s eta 0:00:16
     ----------------------- ------------- 287.6/457.4 MB 10.9 MB/s eta 0:00:16
     ----------------------- ------------- 289.4/457.4 MB 10.8 MB/s eta 0:00:16
     ----------------------- ------------- 292.0/457.4 MB 10.8 MB/s eta 0:00:16
     ----------------------- ------------- 294.4/457.4 MB 10.8 MB/s eta 0:00:16
     ----------------------- ------------- 294.4/457.4 MB 10.8 MB/s eta 0:00:16
     ------------------------ ------------ 296.7/457.4 MB 10.6 MB/s eta 0:00:16
     ------------------------ ------------ 299.6/457.4 MB 10.6 MB/s eta 0:00:15
     ------------------------ ------------ 302.3/457.4 MB 10.6 MB/s eta 0:00:15
     ------------------------ ------------ 305.7/457.4 MB 10.6 MB/s eta 0:00:15
     ------------------------ ------------ 309.1/457.4 MB 10.7 MB/s eta 0:00:14
     ------------------------- ----------- 312.5/457.4 MB 10.7 MB/s eta 0:00:14
     ------------------------- ----------- 316.1/457.4 MB 10.9 MB/s eta 0:00:13
     ------------------------- ----------- 319.8/457.4 MB 10.9 MB/s eta 0:00:13
     -------------------------- ---------- 323.7/457.4 MB 11.1 MB/s eta 0:00:13
     -------------------------- ---------- 325.6/457.4 MB 11.1 MB/s eta 0:00:12
     -------------------------- ---------- 327.9/457.4 MB 11.1 MB/s eta 0:00:12
     -------------------------- ---------- 327.9/457.4 MB 11.1 MB/s eta 0:00:12
     -------------------------- ---------- 328.2/457.4 MB 11.0 MB/s eta 0:00:12
     -------------------------- ---------- 328.2/457.4 MB 11.0 MB/s eta 0:00:12
     -------------------------- ---------- 331.1/457.4 MB 10.8 MB/s eta 0:00:12
     -------------------------- ---------- 333.4/457.4 MB 10.8 MB/s eta 0:00:12
     --------------------------- --------- 336.1/457.4 MB 10.8 MB/s eta 0:00:12
     --------------------------- --------- 338.2/457.4 MB 10.8 MB/s eta 0:00:12
     --------------------------- --------- 340.3/457.4 MB 10.8 MB/s eta 0:00:11
     --------------------------- --------- 342.4/457.4 MB 10.7 MB/s eta 0:00:11
     --------------------------- --------- 343.9/457.4 MB 11.0 MB/s eta 0:00:11
     --------------------------- --------- 343.9/457.4 MB 11.0 MB/s eta 0:00:11
     --------------------------- --------- 343.9/457.4 MB 11.0 MB/s eta 0:00:11
     --------------------------- --------- 345.8/457.4 MB 10.8 MB/s eta 0:00:11
     ---------------------------- -------- 348.4/457.4 MB 10.8 MB/s eta 0:00:11
     ---------------------------- -------- 350.7/457.4 MB 10.9 MB/s eta 0:00:10
     ---------------------------- -------- 352.3/457.4 MB 11.0 MB/s eta 0:00:10
     ---------------------------- -------- 353.4/457.4 MB 11.1 MB/s eta 0:00:10
     ---------------------------- -------- 355.2/457.4 MB 11.2 MB/s eta 0:00:10
     ---------------------------- -------- 357.3/457.4 MB 11.3 MB/s eta 0:00:09
     ----------------------------- ------- 359.7/457.4 MB 11.7 MB/s eta 0:00:09
     ----------------------------- ------- 361.8/457.4 MB 11.7 MB/s eta 0:00:09
     ----------------------------- ------- 364.1/457.4 MB 11.9 MB/s eta 0:00:08
     ----------------------------- ------- 366.7/457.4 MB 12.0 MB/s eta 0:00:08
     ----------------------------- ------- 369.6/457.4 MB 12.0 MB/s eta 0:00:08
     ------------------------------ ------ 372.5/457.4 MB 12.0 MB/s eta 0:00:08
     ------------------------------ ------ 375.7/457.4 MB 12.3 MB/s eta 0:00:07
     ------------------------------ ------ 378.0/457.4 MB 12.3 MB/s eta 0:00:07
     ------------------------------ ------ 379.8/457.4 MB 12.3 MB/s eta 0:00:07
     ------------------------------ ------ 381.9/457.4 MB 12.2 MB/s eta 0:00:07
     ------------------------------- ----- 383.8/457.4 MB 12.1 MB/s eta 0:00:07
     ------------------------------- ----- 385.9/457.4 MB 12.0 MB/s eta 0:00:06
     ------------------------------- ----- 386.1/457.4 MB 12.0 MB/s eta 0:00:06
     ------------------------------- ----- 387.2/457.4 MB 11.8 MB/s eta 0:00:06
     ------------------------------- ----- 389.5/457.4 MB 11.7 MB/s eta 0:00:06
     ------------------------------- ----- 391.4/457.4 MB 11.7 MB/s eta 0:00:06
     ------------------------------- ----- 394.3/457.4 MB 11.6 MB/s eta 0:00:06
     ------------------------------- ----- 395.3/457.4 MB 11.6 MB/s eta 0:00:06
     -------------------------------- ---- 396.1/457.4 MB 11.4 MB/s eta 0:00:06
     -------------------------------- ---- 398.5/457.4 MB 11.4 MB/s eta 0:00:06
     -------------------------------- ---- 398.5/457.4 MB 11.4 MB/s eta 0:00:06
     -------------------------------- ---- 400.8/457.4 MB 11.2 MB/s eta 0:00:06
     -------------------------------- ---- 403.7/457.4 MB 11.1 MB/s eta 0:00:05
     -------------------------------- ---- 406.1/457.4 MB 11.1 MB/s eta 0:00:05
     --------------------------------- --- 408.7/457.4 MB 11.0 MB/s eta 0:00:05
     --------------------------------- --- 410.8/457.4 MB 11.0 MB/s eta 0:00:05
     --------------------------------- --- 410.8/457.4 MB 11.0 MB/s eta 0:00:05
     --------------------------------- --- 412.9/457.4 MB 10.8 MB/s eta 0:00:05
     --------------------------------- --- 417.1/457.4 MB 10.8 MB/s eta 0:00:04
     ---------------------------------- -- 424.9/457.4 MB 10.9 MB/s eta 0:00:03
     ---------------------------------- -- 432.0/457.4 MB 11.2 MB/s eta 0:00:03
     ----------------------------------- - 439.9/457.4 MB 11.3 MB/s eta 0:00:02
     ------------------------------------  445.6/457.4 MB 11.3 MB/s eta 0:00:02
     ------------------------------------  450.4/457.4 MB 11.4 MB/s eta 0:00:01
     ------------------------------------  456.9/457.4 MB 11.4 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.5 MB/s eta 0:00:01
     -------------------------------------- 457.4/457.4 MB 9.6 MB/s eta 0:00:00
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.7.1)
Requirement already satisfied: regex>=2022 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.11.6)
Requirement already satisfied: filelock in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.5)
Requirement already satisfied: jinja2 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\wamp64\www\the-simpsons-ai-analysis\venv\lib\site-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.0.2)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# Load Model

In [3]:
def load_model():
    nlp = spacy.load("en_core_web_trf")
    return nlp

In [4]:
nlp_model = load_model()

c:\wamp64\www\the-simpsons-ai-analysis\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load Dataset

In [5]:
import os 
import sys
import pathlib

folder_path = pathlib.Path().parent.resolve()
sys.path.append(os.path.join(folder_path, '../'))
from utils import load_subtitles_dataset

794

In [6]:
dataset_path = "../data/Subtitles/"
df = load_subtitles_dataset(dataset_path)

['../data/Subtitles\\Simpsons 20x01 Sex Pies and Idiot Scrapes.srt', '../data/Subtitles\\Simpsons 20x02 Lost Verizon.srt', '../data/Subtitles\\Simpsons 20x03 Double Double Boy in Trouble.srt', '../data/Subtitles\\Simpsons 20x04 Treehouse of Horror XIX.srt', '../data/Subtitles\\Simpsons 20x05 Dangerous Curves.srt', '../data/Subtitles\\Simpsons 20x06 Homer and Lisa Exchange Cross Words.srt', '../data/Subtitles\\Simpsons 20x07 Mypods and Broomsticks.srt', '../data/Subtitles\\Simpsons 20x08 The Burns and the Bees.srt', '../data/Subtitles\\Simpsons 20x09 Lisa the Drama Queen.srt', '../data/Subtitles\\Simpsons 20x10 Take My Life Please.srt', '../data/Subtitles\\Simpsons 20x11 How the Test Was Won.srt', '../data/Subtitles\\Simpsons 20x12 No Loan Again Naturally.srt', '../data/Subtitles\\Simpsons 20x13 Gone Maggie Gone.srt', '../data/Subtitles\\Simpsons 20x14 In the Name of the Grandfather.srt', '../data/Subtitles\\Simpsons 20x15 Wedding for Disaster.srt', '../data/Subtitles\\Simpsons 20x16 Eeny Teeny Maya Moe.srt', '../data/Subtitles\\Simpsons 20x17 The Good the Sad and the Drugly.srt', '../data/Subtitles\\Simpsons 20x18 Father Knows Worst.srt', "../data/Subtitles\\Simpsons 20x19 Waverly Hills 9021-D'oh.srt", '../data/Subtitles\\Simpsons 20x20 Four Great Women and a Manicure.srt', '../data/Subtitles\\Simpsons 20x21 Coming to Homerica.srt', '../data/Subtitles\\The Simpsons - 17x01 - The Bonfire of the Manatees.BDRip.x264-TAXES.English.HI.C.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x02 - The Girl Who Slept Too Little.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x03 - Milhouse of Sand and Fog.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x04 - Treehouse of Horror XVI.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x05 - Marges Son Poisoning.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x06 - See Homer Run.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x07 - The Last of the Red Hat Mamas.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x08 - The Italian Bob.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x09 - Simpsons Christmas stories.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x10 - Homers paternity coot.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x11 - Were on the Road to Dohwhere.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x12 - My Fair Laddy.BDRip.x264-TAXES.English.HI.C.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x13 - The Seemingly Never Ending Story.BDRip.x264-TAXES.English.HI.C.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x14 - Bart Has Two Mommies.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x15 - Homer Simpson, This is Your Wife.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x16 - Million Dollar Abie.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x17 - Kiss Kiss, Bang Bangalore.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x18 - The Wettest Stories Ever Told.BDRip.x264-TAXES.English.HI.C.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x19 - Girls just want to have sums.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x20 - Regarding Margie.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x21 - The Monkey Suit.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', '../data/Subtitles\\The Simpsons - 17x22 - Marge and Homer Turn a Couple Play.BDRip-x264-TAXES.English.HI.edit.Addic7ed.com.srt', "../data/Subtitles\\The Simpsons - 19x01 - He Loves To Fly And He D'ohs.en.srt", '../data/Subtitles\\The Simpsons - 19x02 - Homer of Seville.en.srt', '../data/Subtitles\\The Simpsons - 19x03 - Midnight Towboy.en.srt', "../data/Subtitles\\The Simpsons - 19x04 - I Don't Wanna Know Why the Caged Bird Sings.en.srt", '../data/Subtitles\\The Simpsons - 19x05 - Treehouse of Horror XVIII.en.srt', '../data/Subtitles\\The Simpsons - 19x06 - Little Orphan Millie.en.srt', '../data/Subtitles\\The Simpsons - 19x07 - Husbands and Knives.en.srt', '../data/Subtitles\\The Simpsons - 19x08 - Funeral for a Friend.en.srt', '../data/Subtitles\\The Simpsons - 19x09 - Eternal Moonshine of the Simpson Mind.en.srt', '../data/Subtitles\\The Simpsons - 19x10 - E. Pluribus Wiggum.en.srt', "../data/Subtitles\\The Simpsons - 19x11 - That 90's Show.XOR.en.srt", '../data/Subtitles\\The Simpsons - 19x12 - Love  Springfieldian Style.proper caph.en.srt', '../data/Subtitles\\The Simpsons - 19x13 - The Debarted.Caph.en.srt', "../data/Subtitles\\The Simpsons - 19x14 - Dial 'N' for Nerder.hiqt.en.srt", '../data/Subtitles\\The Simpsons - 19x15 - Smoke on the Daughter.PDTV.XOR.en.srt', "../data/Subtitles\\The Simpsons - 19x16 - Papa Don't Leech.PDTV.LOL.en.srt", '../data/Subtitles\\The Simpsons - 19x17 - Apocalypse Cow.PDTV.XOR.en.srt', '../data/Subtitles\\The Simpsons - 19x18 - Any Given Sundance.en.srt', '../data/Subtitles\\The Simpsons - 19x19 - Mona Leaves-a.PDTV.2HD.en.srt', '../data/Subtitles\\The Simpsons - 19x20 - All About Lisa.PDTV.Proper-E7.en.srt', '../data/Subtitles\\The Simpsons - 19x21 - Episode 21.HDTV.LOL.en.srt', "../data/Subtitles\\The Simpsons - 36x01 - Bart's Birthday.WEB.DSNP.en.srt", '../data/Subtitles\\The Simpsons - 36x02 - The Yellow Lotus.WEB.DSNP.en.srt', '../data/Subtitles\\The Simpsons - 36x03 - Desperately Seeking Lisa.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x04 - Shoddy Heat.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x05 - Treehouse of Horror XXXV.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x06 - Women in Shorts.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x07 - Treehouse of Horror Presents  Simpsons Wicked This Way Comes.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x08 - Convenience Airways.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x09 - Homer and Her Sisters.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x10 - The Man Who Flew Too Much.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x11 - Bottle Episode.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x12 - The Flandshees of Innersimpson.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x13 - The Last Man Expanding.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x14 - P.S. I Hate You.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x15 - Abe League of Their Moe.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x16 - Stew Lies.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - 36x17 - Full Heart  Empty Pool.WEB.SuccessfulCrab.en.srt', '../data/Subtitles\\The Simpsons - S06E01 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E02 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E03 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E04 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E05 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E06 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E07 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E08 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E09 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E10 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E11 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E12 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E13 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E14 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E15 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E16 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E17 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E18 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E19 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E20 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E21 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E22 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E23 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E24 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S06E25 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E01 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E02 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E03 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E04 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E05 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E06 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E07 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E08 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E09 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E10 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E11 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E12 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E13 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E14 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E15 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E16 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E17 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E18 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E19 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E20 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E21 WEB.eng.srt', '../data/Subtitles\\The Simpsons - S33E22 WEB.eng.srt', '../data/Subtitles\\The.Simpsons.S01E01.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E02.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E03.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E04.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E05.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E06.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E07.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E08.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E09.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E10.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E11.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E12.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S01E13.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E01.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E02.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E03.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E04.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E05.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E06.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E07.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E08.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E09.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E10.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E11.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E12.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E13.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E14.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E15.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E16.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E17.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E18.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E19.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E20.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E21.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S02E22.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E01.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E02.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E03.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E04.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E05.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E06.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E07.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E08.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E09.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E10.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E11.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E12.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E13.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E14.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E15.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E16.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E17.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E18.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E19.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E20.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E21.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E22.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S03E23.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E01.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E02.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E03.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E04.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E05.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E06.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E07.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E08.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E09.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E10.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E11.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E12.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E13.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E14.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E15.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E16.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E17.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E18.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E19.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E20.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E21.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S04E22.WEBRip.x264-ION10.srt', '../data/Subtitles\\The.Simpsons.S05E01.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E02.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E03.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E04.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E05.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E06.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E07.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E08.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E09.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E10.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E11.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E12.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E13.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E14.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E15.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E16.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E17.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E18.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E19.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E20.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E21.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S05E22.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E01.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E02.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E03.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E04.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E05.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E06.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E07.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E08.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E09.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E10.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E11.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E12.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E13.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E14.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E15.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E16.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E17.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E18.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E19.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E20.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E21.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E22.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E23.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E24.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S07E25.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E01.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E02.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E03.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E04.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E05.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E06.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E07.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E08.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E09.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E10.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E11.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E12.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E13.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E14.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E15.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E16.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E17.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E18.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E19.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E20.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E21.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E22.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E23.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E24.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S08E25.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S09E01.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S09E02.WEBRip.x264-ION10.eng.srt', '../data/Subtitles\\The.Simpsons.S09E

In [7]:
df.head()

  episode                                             script
0    2001  The Simpsons D'oh! BART: Woo-hoo! St. Patrick'...
1    2002  D'oh! BART: Ay, caramba! Out of gas? But how? ...
2    2003  D'oh! Stupid shopping list, turning food into ...
3    2004  Hello. I'd like to vote for president, governo...
4    2005  D'oh! BILL: Bill and Marty here in the middle ...

In [8]:
sample_script = df.iloc[0]['script']
sample_script

"The Simpsons D'oh! BART: Woo-hoo! St. Patrick's Day. I love how they made the river green. Actually, my nuclear plant did that. And now that you know, your life is in danger. Greetings, fellow Irishmen and lady Irishmen. I, Joseph Fitzgerald O'Malley Fitzpatrick O'Donnell... 'The Edge' Quimby, welcome you to Springfield's... ...first booze-free St. Patrick's Day! Come on, people. Your drunken shenanigans destroy this town every year. And Ireland is so much more than the imbibing of spirits. The Irish gave the world the paddy wagon, the shamrock shake, and folk dancing where you don't move your arms. Where's the IRA when you need 'em. We renounced the ways of the gun and the bomb. In the old days we would've been all over that. Oh, no. The Northern Irish are also having a parade. Two kinds of Irish people? What are they fighting over? Who gets to sleep in the bathtub? Actually, those Prots and Cathies have hated each other for centuries. It always comes down to transubstantiation... ...versus consubstantiation. Stop it, both of you! You have a common land, a literature, and the sweetest songs on earth! Too-ra-Ioo-ra-Ioo-ral Too-ra-Ioo-ra-li Hush, my little baby Hush now, don't you cry ALL: Too-ra-Ioo-ra-Ioo-ral Too-ra-Ioo-ra-li Too-ra-Ioo-ra-Ioo-ral That's an Irish lullaby Oh, no! Without the booze, these guys all remember how much they hate each other! This was such a pleasant St. Patrick's Day until the Irish people showed up. Urchins! They took my cupcakes! All right, you unwanted miracles, give back the lady's cupcakes. You don't have the teeth for it. Aye, but we could gum the frosting. Well, if it's good gumming you're after, wouldn't you rather have this lovely cabbage? CHILDREN: Cabbage, cabbage! Here you go, ma'am. Not a sprinkle nor jimmy askew. Thank you so much, Mr... Patrick Farrelly at your service. Marge Simpson. Well, Mr. Farrelly, the least I could do is offer you a cupcake. Mmm. Light, moist, and such a marvelous shape retention. Marge, I own a small bakery. Will you bake for me? Me? A professional baker's employee? Imagine how different my life would be. Here we are at school, kids. Hey, what are those boxes in the back? Cakes! - BOTH: See ya. I'll do it! - Bless your heart. You won't regret it. - I already don't. Homer! I've got great news! I'll use my one phone call to find out all about it! Mulk request change of venue. Green monster cannot get fair trial in downtown Springfield. Granted. Homer Simpson? You're a repeat offender. Three-peat. Bail is set at $25,000. I make that in a year. I suggest you see a bail bondsman. Okay, Simpson. All of your information checks out. I called your boss to verify your employment, and he says you're fired for getting arrested. You'd be amazed how often that happens. Oh! We'll put up your bail money. Just pay us 10 percent and show up for your court date. And if I don't show up? Then you gotta deal with me. The name's Wolf, and I'm a bounty hunter. If someone skips bail, I track 'em down and bring 'em back. I also take a tooth, make a plastic cast, put it on this necklace, then replace the tooth at my expense. Well, time to go back to my world of sleazy bars, tattoo parlors, and greasy spoons. What a great job. And I could use a job right now. Whoa! Not just anyone can be a bounty hunter. You have to pass an online exam. No, wait. They got rid of that. There is a ten-dollar filing fee. But you can get around it. Congratulations. You're now a bounty hunter. Mmm. Okay. I've set my trap. Now to scatter my cheese cubes and the rats will come. Condos! Affordable condos! Bail jumpers welcome! 'Bail jumpers welcome.' That's refreshing, after the cold shoulder we got at the Town Homes at Sterling Point. Let's not get too excited till we... ...find out if it's in a good school district. Well, so wait. Are we telling people now? Stop! In the name of a private citizen with no connection to the law! Now are you gonna come quietly, or do I have to... ...Now let's think about this. If you shoot me, I won't be able to stop you... ...and you'll be free to go. But someone may come after you. Probably not, given your reputation for shooting people who come after you. What I'm trying to say is, not shooting me now... ...would be the biggest mistake of your life. Huh? Bullet-proof glass. Flanders? Yep. I'm just replacing the front window of my store, which was broken in the riot. Young man, what would your mother say... ...if she knew you were shooting nice people in the brain? She'd say that year off from Princeton was the worst decision I ever made. Well, son, if you take responsibility for your actions, this could be the start of a better life for you. Maybe you're right. Maybe I should just... This case is in the bag! Homer, you could've killed him! I sure could've. Thanks to you. Now I can clearly see potential customers walk right past my store. Enjoy your shopping elsewhere. Hey, Ned. I brought you something. What the... - It's your share of the money... ...for bringing in that bail jumper. Ned, I never thought I'd say this, but we make a great team. Us? A team? As the salad said to the soup, I'm all mixed up. We should be bounty hunters together. You're kind and smart. I'm cruel and strong. Together, we're nothing. But together, we're the perfect bounty hunter. Well, I could use money. But you have to promise me something, Homer. Sure. What is it? - We have to do everything by the book. And you have to promise no 'diddilies' or 'doodlies.' My friend, you have a dealaroonie! Mmm. Mmm. Mmm. Mmm. Marge, your talent with cakes is a rare and precious thing. Well, thanks. But I've been wondering. Why do you only have me make spheres, rods, and half-moon shapes? Well, Marge, I'll tell you, Right after I talk to these customers. We're going to a bachelorette party for a really naughty girl. Yeah. We need something tasty and tasteless. I've got just the thing, courtesy of my newest baker. Freshly frosted ass cake. Oh, my God. This is an erotic bakery! BOTH: Mmm. Delicious. Now what do you have in the way of a suggestive cannoli? We have quite a selection. Yes! Oh, boy. - I'll leave you with the book. How could you not tell me this is an erotic bakery? Marge, calm down. For as long as there's been baking, there's been erotic baking. It fills a need and harms no one. Harms no one? Explain that to... Well, what about... I think you forgot about... My number-one customers are married couples, your friends and neighbors. I just made a custom order for the Hibberts. It's an exact replica of the good doctor's... I don't want to know! - It's not what you think it is. Good. It's his penis! - That's exactly what I was thinking! Marge, this is a valuable public service. Without your baking, people like me will be forced into back alleys, repurposing Ho Hos and Ding Dongs. You have a great gift. Don't let it go to waste. Well, okay. This Taser is awesome! Finally, a practical use for electricity. Dear Lord, thank you for creating so many evil criminals for us to bring in. And also, thank you for my partner Homer, who... Did you just Taser my coffee? Just warming it up. Now to melt the cheese in this croissant. And get rid of a little excess earwax. And smoke a relaxing cigar. Homer, can we take it easy on the Taser? - No problem. Our first bail jumper! - Let's roll. Homer, take the Taser out of your pants. No, it looks cool! Boy! Boy! Down in the street there is violence And a lots of work to be done... MAN: Who's there? - Bible salesman. No place to hang out our washing And I can't blame all on the sun, oh no We gonna rock down to Electric A venue And then we'll take it higher Oh, we gonna rock down to Electric A venue And then we'll take it higher Workin' so hard like a soldier Daddy's home! I brought you kids some stuff from work! Here you go, son! Shell casings! Whoa! There's still bullets in some of these! Point them away from your sisters when you hammer them. Yes, sir! What'd you get for me? Something for the sweetest little scientist in the world. A new chemistry set! Dad, is this from a meth lab? - The biggest one in town! This is evidence. Evidence that I love my little girl. Marge, I brought you some flowers. A full dozen this time! No tricks. Homie! I got you something, too! A sterling silver picture frame with pictures of our kids in it. Yes, for now. I guess things are working out pretty good at your bakery job. Maybe we could order one of your cakes for Lisa's birthday. How dare you? - What'd you do that for? Sorry. Sorry. Muscle spasm. I'm not convinced. Still on the fence. Now I believe you. He'll be here sooner or later. So how about a little stakeout music? Homer, I don't think we have the same musical tastes. Well, I like AC/DC. I like their Christian cover band, AD /BC. Kindly deeds done for free Kindly deeds... Done for free Kindly deeds done for free Kindly deeds and they're done for free Kindly deeds and they're done for free I've never seen anyone eat pizza like that. You gotta try it! This way the pepperonis stay intact until they reach your stomach. Then bam! Man! That's harder to swallow than evolution! You've gotta roll it from the point. Here. Let me show you. Not bad. - Now let it unfurl in your stomach. There he is! Kitten whiskers! There's one thing he didn't count on: My reckless indifference to human life! Lord, in your mercy, could you give my friend a stroke? Seymour, those string beans were cooked to perfection. After twenty years, I am finally starting to like you. Just wait for dessert, sir. I made it with you in mind. Outstanding. I'll just shut my eyes and let you place it before me. AGNES: Seymour, what's going on? I'm coming down there! Quick! We'll have to eat from each end. We'll know we're safe when our lips meet in the middle. Homer, you can't drive a car onto a subway. You need a special sticker just to bring a bike! Have you no respect for the law? Hey, it worked, didn't it? Okay, smart guy! You're going in the bag! Wait. I left a sandwich in there. Homer, no. You promised. Everything was supposed to be by the book. You know what your problem is? You haven't become as bad as the people we chase! This partnership is over! I'll tell you what's over: This partnership! You know, if you'd take your foot off the accelerator going downhill, you wouldn't use so much gas. I can't take another word out of you. I can't believe Flanders dumped me. Marge, do we have any more of your extra-Iong Twinkies? Oh, no! Those were for Mr. Smithers' commitment ceremony! Marge, what's going on? Homie, I've got a confession to make. I'm an erotic baker. I hid it all in the one place you'd never look. Marge, I could see you withholding sex or withholding cake. But withholding sexy cake? I know we have to move past this but I don't see how. Homie, what do you say we go to bed? You, me, and the cake? First, why don't you and I and the cake take a shower? Oh. Lucky Jim, I'm out of the bounty hunting business. Not so fast, Ned. I got one more bail jumper for you to pick up. Forget it! I'm turning in my... Well, I don't really have anything to turn in. So that's that! I suggest you call Homer Simpson! This is one jumper that Homer can't catch. Homer? - Seems he never showed up in court... ...on his St. Patrick's Day arrest. - Not interested. All right. If you don't want the job, I'll just give it to one of these guys. I'm sure they're all competent professionals. But you'd best leave it to me. Hello? Hello? Anybody home? You jumped bail, Homer. I gotta bring you in. What have you done to my family? I figured a good time to pick you up was when they were at Lisa's recital. And how did you know I wouldn't be there? Lucky guess. Well, you'll never take me alive! Forgot my keys. I loved you, man! - For the last few weeks. But most of the time I've known you, you've treated me like dirt. You hang onto resentment like a Confederate widow! I forgave you for accidentally killing my wife. Yeah. But you hold onto the big things! The point is the more I got to know you, the more I got to like you. I like you, too. But you broke the law. So I gotta bring you in. So it's gonna be like that, eh? I got you, my friend. Thanks. But what are you holding onto? Well, I'm... Now all we have to do is get out before the concrete hardens. Damn it. 'Lest I come and strike the earth with a curse.' Thus ends the Book of Malachi. I guess I did know the whole Old Testament by heart. Out with the Old, in with the New. Testament that is. Matthew 1.'The book of the genealogy of Jesus Christ, the son of David, 'the son of Abraham. 'Abraham became the father of Isaac. Isaac became the father of Jacob. 'Jacob became the father of Judah and his brothers. 'Judah became the father of Perez and Zarah by Tamar.' Simpson, we're gonna put you away for a long, long time. Make it life and you've got a deal. MARGE: Don't feel too bad, Homie. You'll be free tomorrow. And I used all my new baking skills... ...to make a special cake to remind you of me. Baby! Thanks, Marge."

In [9]:
sentences = sent_tokenize(sample_script)

In [10]:
sentences = sentences[60:90]

In [11]:
sentence = ".".join(sentences)

In [12]:
sentence

"Homer Simpson?.You're a repeat offender..Three-peat..Bail is set at $25,000..I make that in a year..I suggest you see a bail bondsman..Okay, Simpson..All of your information checks out..I called your boss to verify your employment, and he says you're fired for getting arrested..You'd be amazed how often that happens..Oh!.We'll put up your bail money..Just pay us 10 percent and show up for your court date..And if I don't show up?.Then you gotta deal with me..The name's Wolf, and I'm a bounty hunter..If someone skips bail, I track 'em down and bring 'em back..I also take a tooth, make a plastic cast, put it on this necklace, then replace the tooth at my expense..Well, time to go back to my world of sleazy bars, tattoo parlors, and greasy spoons..What a great job..And I could use a job right now..Whoa!.Not just anyone can be a bounty hunter..You have to pass an online exam..No, wait..They got rid of that..There is a ten-dollar filing fee..But you can get around it..Congratulations..You're now a bounty hunter."

# Run Model

In [13]:
doc = nlp_model(sentence)

In [14]:
doc.ents

(Homer Simpson?.You're,
 Three,
 25,000,
 a year,
 Simpson,
 10 percent,
 Wolf,
 ten-dollar)

In [15]:
for entity in doc.ents:
    print(entity, entity.label_)

Homer Simpson?.You're PERSON
Three CARDINAL
25,000 MONEY
a year DATE
Simpson PERSON
10 percent PERCENT
Wolf PERSON
ten-dollar MONEY

In [ ]:
def get_ners_inference(script):
    script_sentences = sent_tokenize(script)

    ner_output = []

    for sentence in script_sentences:
        doc = nlp_model(sentence)
        ners = set()
        for entity in doc.ents:
            if entity.label_ =="PERSON":
                full_name = entity.text
                first_name = entity.text.split(" ")[0] 
                first_name = first_name.capitalize().strip()
                first_name = "Homer" if first_name == "Homie" else first_name # Replace "Homie" with "Homer"
                # Exclude "Simpson" and "Mmm" as they are not first names
                if first_name != "Simpson" and first_name != "Mmm":
                    ners.add(first_name)
                    
        ner_output.append(ners)

    return ner_output

In [ ]:
df = df.head(5) # For Testing

df

  episode                                             script
0    2001  The Simpsons D'oh! BART: Woo-hoo! St. Patrick'...
1    2002  D'oh! BART: Ay, caramba! Out of gas? But how? ...
2    2003  D'oh! Stupid shopping list, turning food into ...
3    2004  Hello. I'd like to vote for president, governo...
4    2005  D'oh! BILL: Bill and Marty here in the middle ...
5    2006  D'oh! Lemonade! Sweet sunshine in your mouth! ...
6    2007  D'oh! SANTAS: Ho-ho-ho. ALL: O Christmas Tree,...
7    2008  The Simpsons D'oh! Sir, we're two minutes from...
8    2009  D'oh! Worst couch gag ever. Why do we have to ...
9    2010  D'oh! Aha! Today we induct the newest honoree ...

In [18]:
df['ners'] = df['script'].apply(get_ners_inference)

In [19]:
df

,episode,script,ners
0,2001,The Simpsons D'oh! BART: Woo-hoo! St. Patrick'...,"[{}, {}, {}, {}, {}, {}, {}, {Joseph, The}, {}..."
1,2002,"D'oh! BART: Ay, caramba! Out of gas? But how? ...","[{}, {Caramba, Bart}, {}, {}, {}, {Rockefeller..."
2,2003,"D'oh! Stupid shopping list, turning food into ...","[{}, {}, {Bart}, {}, {}, {}, {Homer}, {}, {}, ..."
3,2004,"Hello. I'd like to vote for president, governo...","[{}, {}, {}, {}, {}, {}, {}, {Mccain}, {}, {},..."
4,2005,D'oh! BILL: Bill and Marty here in the middle ...,"[{}, {Bill, Marty}, {}, {Marty}, {}, {}, {}, {..."
5,2006,D'oh! Lemonade! Sweet sunshine in your mouth! ...,"[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
6,2007,"D'oh! SANTAS: Ho-ho-ho. ALL: O Christmas Tree,...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
7,2008,"The Simpsons D'oh! Sir, we're two minutes from...","[{}, {}, {}, {}, {}, {}, {Ted}, {}, {}, {}, {}..."
8,2009,D'oh! Worst couch gag ever. Why do we have to ...,"[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
9,2010,D'oh! Aha! Today we induct the newest honoree ...,"[{}, {}, {Paul, Poochie, Duffman}, {Vance}, {}..."

# Character Network

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from pyvis.network import Network

In [21]:
def generate_character_network(df):

    windows=10 # Number of sentences to look back for relationships
    entity_relationship = []

    for row in df['ners']:
        previous_entities_in_window = []

        for sentence in row:
            previous_entities_in_window.append(list(sentence))
            previous_entities_in_window = previous_entities_in_window[-windows:]

            # Flatten 2D List into 1D List
            previous_entities_flattened = sum(previous_entities_in_window, [])

            for entity in sentence:
                for entity_in_window in previous_entities_flattened:
                    if entity.lower() != entity_in_window.lower(): # Lowercase to avoid duplicates
                        entity_relationship.append(sorted([entity, entity_in_window])) # Sort to avoid duplicates
    
    relationship_df = pd.DataFrame({'value': entity_relationship})
    relationship_df['source'] = relationship_df['value'].apply(lambda x: x[0])
    relationship_df['target'] = relationship_df['value'].apply(lambda x: x[1])
    relationship_df = relationship_df.groupby(['source', 'target']).count().reset_index()
    relationship_df = relationship_df.sort_values('value', ascending=False)

    return relationship_df

In [22]:
relationship_df = generate_character_network(df)

In [23]:
relationship_df

      source   target  value
373    Homer    Marge     38
402    Homer    Vance     30
368    Homer     Lisa     28
365    Homer    Lenny     26
105     Bart     Lisa     19
..       ...      ...    ...
641     Paul    Vance      1
645  Poochie    Vance      1
646    Prots  Urchins      1
647  Pumpkin      The      1
648  Quenley    Simon      1

[667 rows x 3 columns]

In [24]:
relationship_df = relationship_df.sort_values('value', ascending=False)
relationship_df = relationship_df.head(200)

In [25]:
G = nx.from_pandas_edgelist(
    relationship_df, 
    source='source', 
    target='target', 
    edge_attr='value',
    create_using=nx.Graph()
)

net = Network(notebook=True, width="1000px", height="700px", bgcolor="#222222", font_color="white", cdn_resources="remote")
node_degree = dict(G.degree)

nx.set_node_attributes(G, node_degree, 'size')
net.from_nx(G)
net.show("simpsons.html")

simpsons.html